let name = "Harry";
let school = "Ideal Internation Academy";
let grade = "A+";
let section = "B";
let rollno = 10;
let science_mark = 50;
let math_mark = 70;
let social_mark = 70;
console.log(name);
console.log(school);
console.log(grade);
console.log(section);
console.log(rollno);
console.log(science_mark);
console.log(math_mark);
console.log(social_mark);